### ISSUE TITLE
The current version (1.0.1dev) is not on PyPI

### ISSUE THREAD

**Issue by sylvainemery** [devartis/passbook#27]
I'm using your awesome project in a library of mine, and I use my library in one of my projects.
I'm mixing pip and setuptools to install everything and pip won't fetch the last version on github, but it tries to get it on PyPI. Alas, only the version 1.0.0 is on PyPI!
Could you make a new release? Maybe 1.0.2?

Thanks a lot!

**Comment by fara** [comment]
Hi Sylvain, thanks for the feedback. I've just made a release to PyPI with the latest version 1.0.1. The master version on Github is now 1.0.2dev
Best,

**Comment by sylvainemery** [comment]
Thanks a lot!
