### ISSUE TITLE
iOS 9 barcodes key not supported

### ISSUE THREAD

**Issue by davidcorry** [devartis/passbook#30]
Apple introduced `barcodes` as a replacement to `barcode` in iOS9, which is now required to display a barcode. `barcodes` is an array of `barcode` items. `barcode` as a top-level key is now depreciated, although it's allowed to keep pass compatibility with iOS 8.

`barcodes` also supports a new format: `PKBarcodeFormatCode128`.

[Here is where Apple discusses this change.](https://developer.apple.com/library/ios/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW5)

**Comment by mbaechtold** [comment]
This issue could be closed because it has been resolved with #31.

**Comment by johnksterling** [comment]
Agree
