### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by mbaechtold** [devartis/passbook#40]
I'm in the process of adding support for Python 3. 

Since `M2Crypto` is not compatible with Python 3 I'm looking into alternatives. The only crypto primitive used for creating passcode files is signing the manifest, so we don't really need to rely on a full-fledged crypto library (but it would be better because they know better than I do). 

Anyway, the work is done in a branch of my fork at https://github.com/mbaechtold/passbook/tree/python3-m2crypto. Since other people are trying to do the same (at least @ssyms) I thought we should join forces.

~~My next step is to remove my custom signing library with pyOpenSSL which is compatible with Python 3 but does not officially support detached PKCS#7 signatures.~~

In the meantime, feel free to test my code at will.

Update from 2020-05-17: `M2Crypto` has added support for Python 3 in the meantime. So we may keep this dependency.

**Comment by rixx** [comment]
I abandoned my branch way back when I started it to use https://github.com/oeegor/wallet-py3k instead. Did everything I wanted to, and I'm willing to bear one sys call for a working library (although I understand why you might not want that).

**Comment by Shamil-R** [comment]
Hello! Any body support this project? Or will be better to turn on  https://github.com/oeegor/wallet-py3k?
Thanks
