### ISSUE TITLE
How I add currencyCode in primaryFields?

### ISSUE THREAD

**Issue by imjaypatel** [devartis/passbook#42]
How can I added _currencyCode_ in `addPrimaryField` method. I wanna create following json in _addPrimaryField_ method,
```
  "storeCard" : {
    "primaryFields" : [
      {
        "key" : "balance",
        "label" : "remaining balance",
        "value" : 21.75,
        "currencyCode" : "USD"
      }
    ],
```
As I check _addPrimaryField_ method there is only 3 parameter are accept.
`passfile.passInformation.addPrimaryField('balance', 21.75, 'remaining balance')`

I was found _CurrencyField_ Class but I was not understand how to access _CurrencyField_ Class with _addAuxiliaryField_ Class. Thank you.

**Comment by mbaechtold** [comment]
I have not tested this, but it should be possible to directly append to `primaryFields` instead of using the helper method `addPrimaryField()`:

```python
balance_field = CurrencyField(
  'balance',
  float(22.00),
  'test label',
  'USD',
)

passfile.passInformation.primaryFields.append(balance_field)
```

**Comment by mbaechtold** [comment]
I'm closing this issue due to its age.
