### ISSUE TITLE
How to change barcode format

### ISSUE THREAD

**Issue by kevxlreee** [devartis/passbook#45]
How to change the barcode format to something other than the default PDF417?

If I do `passfile.barcode = Barcode(message = 'message', format=BarcodeFormat.CODE128)` I get a NameError - name 'BarcodeFormat' is not defined.

Sorry for my noob question :)

**Comment by mbaechtold** [comment]
Did you import the class `BarcodeFormat`?

`from passbook.models import BarcodeFormat`

If you did, could you please provide a more complete example of your code?

**Comment by kevxlreee** [comment]
Oops...I hadn't imported that class. It works now :)

Thanks for your help!
