### ISSUE TITLE
Grouping Identifier

### ISSUE THREAD

**Issue by benydc** [devartis/passbook#46]
Are you able to add grouping identifier to the Pass class?

**Comment by mbaechtold** [comment]
I see, this is described in https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html but missing in this library. 

We happily accept pull requests if you want to contribute this feature.

**Comment by sbbastos** [comment]
Hi,

How I create a Grouping Identifier to grouping the passes?

**Comment by mbaechtold** [comment]
@sbbastos, you could try to set a property `groupingIdentifier` on an instance of the `Pass` class:

```
from passbook.models import Pass

my_pass = Pass(...). # see README.md
my_pass.groupingIdentifier = "Foo"
```

**Comment by sbbastos** [comment]
yes @mbaechtold , but can the value be anything like your exemple  or must be a predefined value? 
For exemple, Like we set the Team identifier. 
If Yes, what moment I create it?

**Comment by sbbastos** [comment]
A friend sent me some expired tickets and I got the answer.

The airline concatenates the locator and name and puts it as a group identifier.

I thought groupingIdentifier was issued by Apple.

Thanks

**Comment by mbaechtold** [comment]
Seems like this issue has been solved, so I'm closing it.
