### ISSUE TITLE
Discussion: drop support for Python < 3?

### ISSUE THREAD

**Issue by mbaechtold** [devartis/passbook#49]
I'm reaching out to the owners of this repo (i.e. @fara and @poligarcia) about the impeding end of support of Python 2.7.

Would it be ok for you to drop support for Python 2.7 by Januar 1st, 2020? This would make the update to Python 3 much easier. 

I already have started adding support for Python 3 in  https://github.com/devartis/passbook/issues/40 but did not feel comfortable enough to merge it.

**Comment by fara** [comment]
Hi @mbaechtold, I think it's OK. That date will match with [Python sunset](https://www.python.org/doc/sunset-python-2/). Users still using Python2 will have to use older releases.

**Comment by mbaechtold** [comment]
Closed by the pull request #43
