### ISSUE TITLE
Clarify license on pypi.org 

### ISSUE THREAD

**Issue by nicoinn** [devartis/passbook#56]
The license on Pypi.org is states as `Copyright (c) 2012 devartis`
See: https://pypi.org/project/Passbook/

While in this repo, it clearly states that the package is under MIT license. 

Could you please clarify/update the listing on pypi ?

**Comment by fara** [comment]
We can remove the copyright claim @nicoinn 

Can you please create a PR with the changes?
Need to modify https://github.com/devartis/passbook/blob/master/LICENSE.txt and update the version number of the package

**Comment by mbaechtold** [comment]
This issue has been solved in the pull request https://github.com/devartis/passbook/pull/57, so I'm closing it. Please reopen it if I'm mistaken.
