### ISSUE TITLE
No module named 'StringIO'

### ISSUE THREAD

**Issue by agn-7** [devartis/passbook#65]
By the execution of the following line I encounter with the following error:

```python
from passbook.models import Pass

```

Out:

```
File ~/.local/lib/python3.10/site-packages/passbook/models.py:11, in <module>
      9     from cStringIO import StringIO
     10 except ImportError:
---> 11     from StringIO import StringIO
     13 import hashlib
     14 import zipfile

ModuleNotFoundError: No module named 'StringIO'
```

**Comment by bahmanshams** [comment]
Support for Python 3 has landed in the master branch. You could give it a try by installing it from GitHub —
`git+https://github.com/devartis/passbook.git` instead of pypi package.
